// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCy7jNZQTYJJ6ffBkbatcY-DPiRQzZ4oZg',
    appId: '1:1012124243868:web:afbe1c2f3b53d5f81d5a59',
    messagingSenderId: '1012124243868',
    projectId: 'giahuy-7d9bc',
    authDomain: 'giahuy-7d9bc.firebaseapp.com',
    databaseURL: 'https://giahuy-7d9bc-default-rtdb.firebaseio.com',
    storageBucket: 'giahuy-7d9bc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPhwsq3aEL3LrniauOpBhdIvTDCXR772s',
    appId: '1:1012124243868:android:9831380cb461213d1d5a59',
    messagingSenderId: '1012124243868',
    projectId: 'giahuy-7d9bc',
    databaseURL: 'https://giahuy-7d9bc-default-rtdb.firebaseio.com',
    storageBucket: 'giahuy-7d9bc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0x8wU48_L3zR3TjpzJ0xBepg5E5ylIoQ',
    appId: '1:1012124243868:ios:8146afddcc14027d1d5a59',
    messagingSenderId: '1012124243868',
    projectId: 'giahuy-7d9bc',
    databaseURL: 'https://giahuy-7d9bc-default-rtdb.firebaseio.com',
    storageBucket: 'giahuy-7d9bc.firebasestorage.app',
    iosBundleId: 'com.example.pAppgarden',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0x8wU48_L3zR3TjpzJ0xBepg5E5ylIoQ',
    appId: '1:1012124243868:ios:8146afddcc14027d1d5a59',
    messagingSenderId: '1012124243868',
    projectId: 'giahuy-7d9bc',
    databaseURL: 'https://giahuy-7d9bc-default-rtdb.firebaseio.com',
    storageBucket: 'giahuy-7d9bc.firebasestorage.app',
    iosBundleId: 'com.example.pAppgarden',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCy7jNZQTYJJ6ffBkbatcY-DPiRQzZ4oZg',
    appId: '1:1012124243868:web:73fe182df85c3b951d5a59',
    messagingSenderId: '1012124243868',
    projectId: 'giahuy-7d9bc',
    authDomain: 'giahuy-7d9bc.firebaseapp.com',
    databaseURL: 'https://giahuy-7d9bc-default-rtdb.firebaseio.com',
    storageBucket: 'giahuy-7d9bc.firebasestorage.app',
  );

}